### PR TITLE
Add graphql on the client and server

### PR DESCRIPTION
**Pull request by sync**

### CODE REVIEW

**Comment by jaydenseric** [comment]
I think you still need to set up [`withGraphQLConfig`](https://github.com/jaydenseric/next-graphql-react#function-withgraphqlconfig)?

**Comment by sync** [comment]
deploying now thank you

**Comment by sync** [comment]
same error: https://next-level-fif8ibmae.now.sh/

**Comment by sync** [comment]
it's fine anyway i am not gonna do anything with it, was just curious about the failure

**Comment by sync** [comment]
see https://github.com/sync/next-level/pull/11

**Pull request closed without merging**
